### ISSUE TITLE
Problem computing loss for Convolutional Autoencoder

### ISSUE THREAD

**Issue by ManuelJNunez** [ManuelJNunez/TFG#77]
**Expected Behavior**

It should compute the loss without throwing an exception.

**Current Behavior**

It throws an exception because the forward method of the ConvAutoencoder class retrieves a tuple, not a Tensor.

**Steps to Reproduce**

Run the following command commenting the `@job` decorator:

```
python src/cae.py
```

**Comment by ManuelJNunez** [comment]
I have the same problem with `generate_confusion_matrix`:

```plaintext
Traceback (most recent call last):
  File "src/cae.py", line 123, in <module>
    main()
  File "src/cae.py", line 87, in main
    train_cmatrix = generate_confusion_matrix(train_dl, model)
  File "/home/mjnunez/Asignaturas/4-CUARTO/TFG/TFG/src/ml/utils/utils.py", line 110, in generate_confusion_matrix
    pred_prob = model(data).cpu().detach().numpy()
AttributeError: 'tuple' object has no attribute 'cpu'
```
